spring.application.name=tms

server.port=8080

spring.datasource.url=jdbc:mysql://localhost:5432/tms
spring.datasource.username=postgres
spring.datasource.password=12345678

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=7fK9mQ2xVb8RzN4pLs1YwE6uHd3JcT5aXp0GkM8nQv2Zr7UyBf4Hs9Ld6Pw1Xe3Ct
jwt.expiration=86400000